services:
  apiserver:
    build:
      context: ../apiserver
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../apiserver:/usr/src/app
      - ../runner/env/.env.development:/usr/src/app/.env.development
    env_file:
      - ./env/.env.development
    profiles:
      - dev

  apiserver_prod:
    container_name: apiserver_prod
    build:
      context: .
      dockerfile: ../apiserver/docker/production/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../apiserver:/usr/src/app
      - ../runner/env/.env.production:/usr/src/app/.env.production
    env_file:
      - ./env/.env.production
    profiles:
      - prod

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: